steps:
  - name: 'Destroy Current'
    args: [ './destroy.bash', '--foo' ]

  - name: 'Deploy new'
    args: [ './deploy.bash', '--foo' ]

  - name: 'Run Tests'
    args: [ './test.bash', '--foo', ${BRANCH_NAME} ]

