apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app":"istio-ingressgateway","install.operator.istio.io/owning-resource":"example-istiocontrolplane","install.operator.istio.io/owning-resource-namespace":"istio-system","istio":"ingressgateway","operator.istio.io/component":"IngressGateways","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.6.4","release":"istio"},"name":"istio-ingressgateway-service-account","namespace":"istio-system"}}
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: example-istiocontrolplane
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: ingressgateway
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.6.0
    release: istio
  name: istio-ingressgateway-service-account
  namespace: istio-system
  resourceVersion: "207667"
  selfLink: /api/v1/namespaces/istio-system/serviceaccounts/istio-ingressgateway-service-account
  uid: 1c13194f-bf5a-11ea-8564-42010a8001fb