## Copyright 2019 The Tranquility Base Authors
## 
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
## 
##     http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.

{{- if .Values.gateway.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: {{ .Values.gateway.portNumber }}
      name: {{ .Values.gateway.portName }}
      protocol: {{ .Values.gateway.portProtocol }}
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "itop.fullname" . }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.gateway.name }}
  http:
  - route:
    - destination:
        host: {{ include "itop.fullname" . }}
        port:
          number: {{ .Values.service.port }}
{{- end }}
