imports:
- path: tranquility-base.jinja

resources:
- name: tranquility-base
  type: tranquility-base.jinja
  properties:
    zone: 'europe-west2-a'
    rootId: '649882709448'
    billingAccountId: '01A2F5-73127B-50AE5B'